#!/bin/bash
# HETZNER SUNUCU TELEGRAM BOT ANALİZİ VE ÇÖZÜMÜ

echo "🔍 MEVCUT DURUM ANALİZİ:"
echo "✅ Sunucu çalışıyor: 1 gün uptime"
echo "✅ Telegram bot dosyaları mevcut: /root/PlanB_Motoru/"
echo "❌ planb.service bulunamadı"
echo "❌ Docker yüklü değil"
echo ""

echo "🎯 SORUN: Telegram bot systemd servisi olarak kurulmamış!"
echo "Bu yüzden sunucu restart olduğunda bot durur."
echo ""

echo "💡 ÇÖZÜM PLANI:"
echo "1. Ana telegram bot dosyasını belirle"
echo "2. Systemd servis dosyası oluştur"
echo "3. Servisi enable & start yap"
echo "4. Auto-restart politikası ekle"
echo ""

echo "📋 GEREKLİ KOMUTLAR (SSH'ta çalıştırılacak):"
echo ""
echo "# 1. Durum analizi"
echo "cd /root/PlanB_Motoru"
echo "ls -la telegram_full_trader_with_sentiment.py"
echo "ps aux | grep python"
echo "ps aux | grep telegram"
echo ""
echo "# 2. Ana bot dosyasını test et"
echo "python3 telegram_full_trader_with_sentiment.py &"
echo "sleep 5"
echo "kill %1"
echo ""
echo "# 3. Systemd servis dosyası oluştur"
echo "cat > /etc/systemd/system/planb.service << 'EOF'"
echo "[Unit]"
echo "Description=PlanB Motoru Telegram Bot"
echo "After=network.target"
echo "StartLimitIntervalSec=0"
echo ""
echo "[Service]"
echo "Type=simple"
echo "Restart=always"
echo "RestartSec=10"
echo "User=root"
echo "WorkingDirectory=/root/PlanB_Motoru"
echo "ExecStart=/usr/bin/python3 telegram_full_trader_with_sentiment.py"
echo "Environment=PYTHONPATH=/root/PlanB_Motoru"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF"
echo ""
echo "# 4. Servisi aktifleştir"
echo "systemctl daemon-reload"
echo "systemctl enable planb"
echo "systemctl start planb"
echo "systemctl status planb"
echo ""
echo "🚀 SONUÇ: Bilgisayar kapansa bile Telegram mesajları gelmeye devam eder!"